---
- name: Setup performance server
  hosts: perf_server
  become: true
  tasks:
    - name: Add node 8 repo
      shell: "sudo curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash"

    - name: Install nodejs
      yum:
        name: nodejs

    - name: Install artillery
      npm:
        name: artillery
        global: True

    - name: Create module directory for custom module
      file:
        path: /usr/lib/node_modules/artillery-plugin-metrics-by-endpoint/
        state: directory

    - name: Install custom artillery-plugin-metrics-by-endpoint
      copy:
        src: "artillery-plugin-metrics-by-endpoint/{{ item }}"
        dest: /usr/lib/node_modules/artillery-plugin-metrics-by-endpoint/
      loop:
        - package.json
        - index.js

    - name: Create artillery directory
      file:
        path: /opt/artillery
        state: directory

    - name: Create reports directory
      file:
        path: /opt/artillery/reports
        state: directory

    - name: Copy artillery scenario
      copy:
        src: "{{ item }}"
        dest: /opt/artillery/
      loop:
        - scenario.yml
        - user_list
        - word_list_fr
