version: '3.2'

services:
  postgres:
    image: postgres:10.1
    volumes:
      - "./api/postgres_data:/var/lib/postgresql/data"
    env_file:
      - env_file
    networks:
      - db_nw

  flask:
    build: dockerfiles/flask
    volumes:
      - ./api:/opt/services/flaskapp/src
      - type: bind
        source: ./api/ftp_mirrors
        target: /opt/services/flaskapp/src/ftp_mirrors
        read_only: true
    environment:
      - ENV=${ENV:-development}
      - EXPORT_TOKEN=$EXPORT_TOKEN
      - MAILJET_API_KEY=${MAILJET_API_KEY:-20594a94ba962e549a7d5b1c3c6cd1ce}
      - MAILJET_API_SECRET=${MAILJET_API_SECRET:-9c55d1afb02b90e9150b316dc50a8dd6}
    env_file:
      - env_file
    networks:
      - db_nw
      - web_nw
    depends_on:
      - postgres

  nginx:
    build: dockerfiles/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    networks:
      - web_nw
    depends_on:
      - flask

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  postgres_data:
