---
- name: Install Jupyterhub
  hosts: jupyterhub
  become: true
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install setuptools
      apt:
        name: 'python3-setuptools'
        state: present

    - name: Create jupyterhub directory
      file:
        path: /opt/jupyterhub
        state: directory
        owner: ubuntu

    - name: Copy requirements.txt
      copy:
        src: requirements.txt
        dest: /opt/jupyterhub/requirements.txt
        owner: ubuntu

    - name: Install python requirements
      pip:
        requirements: /opt/jupyterhub/requirements.txt
        executable: /opt/tljh/user/bin/pip
      tags: pip

    - name: Install git required packages
      apt:
        name: git-core
        update_cache: yes
      tags: git

    - name: Copy tljh config
      template:
        src: tljh_config.yml.j2
        dest: /opt/tljh/config/config.yaml
        owner: ubuntu
        mode: u=rw,g=r,o=r
      tags: copy-tljh
      notify: Reload tljh config

    - meta: flush_handlers

    - name: Copy create_database_tunnel.sh
      template:
        src: create_database_tunnel.sh.j2
        dest: /opt/jupyterhub/create_database_tunnel.sh
        owner: ubuntu
        mode: u=rwx,g=rx,o=rx
      tags: copy

    - name: Check if scalingo cli is installed
      stat:
        path: /usr/local/bin/scalingo
      register: scalingo_cli
      tags: 'scalingo'

    - name: Get scalingo cli install script
      get_url:
        url: https://cli-dl.scalingo.io/install
        dest: /tmp/install
      when: scalingo_cli.stat.exists == false
      tags: 'scalingo'

    - name: Run scalingo install script
      command:  bash /tmp/install
      when: scalingo_cli.stat.exists == false
      tags: 'scalingo'

    - name: Copy connect_to_database.service
      copy:
        src: connect_to_database.service
        dest: /etc/systemd/system/connect_to_database.service
        owner: ubuntu

    - name: Start connection to database service
      systemd:
        state: started
        name: connect_to_database.service
        enabled: yes


  handlers:
    - name: Reload tljh config
      command: tljh-config reload
