version: 2
jobs:
  tests-script-pc:
    machine:
      image: circleci/classic:latest
    working_directory: ~/pass-culture
    steps:
      - checkout
      - run:
          name: Install libraries
          command: |
            sudo apt-get update
            sudo apt-get install -y realpath
            sudo ./pc symlink
      - run:
          name: Running PC Tests
          command: |
            cd tests
            ./run_tests.sh


workflows:
  version: 2
  commit:
    jobs:
      - tests-script-pc