- name: Pip uninstall dependencies
  pip:
    name: ['requests', 'six', 'urllib3']
    state: absent

- name: Yum reinstall dependecies
  yum:
    name: ['python-requests', 'python-six', 'python-urllib3']

- name: Install cerbot
  yum:
    name: ['certbot', 'python2-certbot-nginx']

- name: Install or update python requirements
  pip:
    name: ['cffi', 'six', 'requests==2.6.0']
    state: latest

- name: Add crontab to renew certificates
  cron:
    minute: "30"
    hour: "2"
    weekday: "1"
    job: "/usr/bin/certbot renew >> /var/log/le-renew.log"

- name: Add crontab to reload server
  cron:
    minute: "35"
    hour: "2"
    weekday: "1"
    job: "/usr/sbin/nginx reload"
