- name: check if certificate file exists
  stat:
    path: "{{ letsencrypt_ssl_dir }}/{{ service_host }}/fullchain.pem"
  register: certificate_file

- name: Create certificate
  shell: certbot certonly --webroot --email {{ service_admin_email }} --agree-tos --webroot-path=/usr/share/nginx/html -d {{ service_host }};
  when:  certificate_file.stat.exists

#- name: Add https nginx configuration
#  template:
#    src: service.https.conf.j2
#    dest: /etc/nginx/sites-available/{{ service_name }}.https.conf
#    owner: www-data
#    group: www-data
#    mode: 0644
#
#- name: Add external https nginx symlink
#  file:
#    src: /etc/nginx/sites-available/{{ service_name }}.https.conf
#    dest: /etc/nginx/sites-enabled/{{ service_name }}.https
#    owner: www-data
#    group: www-data
#    state: link

#- name: reload nginx
#  service:
#    name: nginx
#    state: reloaded