- name: check if certificate file exists
  stat:
    path: "{{ letsencrypt_ssl_dir }}/{{ service_host }}/fullchain.pem"
  register: certificate_file

- name: Create certificate
  shell: certbot certonly --webroot --email {{ service_admin_email }} --agree-tos --webroot-path=/usr/share/nginx/html -d {{ service_host }};
  when:  certificate_file.stat.exists

- name: Add nginx configuration with SSL certificate
  template:
    src: nginx_conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify: 'nginx'
