- firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
  notify: 'Firewalld'
  tags: 'firewalld'

- firewalld:
    port: 443/tcp
    permanent: yes
    state: enabled
  notify: 'Firewalld'
  tags: 'firewalld'
