- name: Create Sentry directory
    file:
      path: /opt/sentry
      state: directory
    tags:
      - 'sentry'

- name: Clone Sentry project
  git:
    repo: 'https://github.com/getsentry/onpremise'
    dest: /opt/sentry
    update: no
  tags:
    - 'sentry'

- name: Update Sentry configuration
  blockinfile:
    path: /opt/sentry/sentry.conf.py
    block: |
      #####################
      # GOOGLE AUTH LOGIN #
      #####################

      SENTRY_OPTIONS['auth-google.client-id'] = "{{ google_client_id }}"
      SENTRY_OPTIONS['auth-google.client-secret'] = "{{ google_client_secret }}"
  tags:
    - 'sentry'

- name: check if sentry/.env file exists
  stat:
    path: /opt/sentry/.env
  register: sentry_env_file

- name: Run Sentry install.sh
  command: ./install.sh >> installation_logs.txt
  args:
    chdir: /opt/sentry
  when: sentry_env_file.stat.exists == false
  tags:
    - 'sentry'

- name: Run compose to start containers
  docker_service:
    project_src: /opt/sentry
    state: present
  tags:
    - 'sentry'