---
- name: Install Sentry server
  hosts: sentry
  become: true
  tasks:
    - import_tasks: tasks/install_docker.yml
      tags:
        - 'docker'

    - import_tasks: tasks/install_git.yml
      tags:
        - 'git'

    - import_tasks: tasks/install_sentry.yml
      tags:
        - 'sentry'

    - import_tasks: tasks/firewalld.yml
      tags:
        - 'firewalld'

    - import_tasks: tasks/install_nginx.yml
      tags:
        - 'nginx'

    - name: Check if dhparams file exists
      stat:
        path: /etc/ssl/certs/dhparam.pem
      register: dhparams_file

    - name: Generate  dhparams file
      shell: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
      when: dhparams_file.stat.exists == false

    - import_tasks: tasks/certificate.yml
      tags:
        - 'certificate'

  handlers:
    - name: restart_firewalld
      service:
        name: firewalld
        state: restarted

    - name: reload nginx
      service:
        name: nginx
        state: reloaded

#    - name: Configure administrator account
#      expect:
#        command: docker-compose run --rm web createuser
#        responses:
#          Question:
#            - sentry_admin_email
#            - sentry_admin_password
#            - sentry_admin_password
#            - 'y'
#      no_log: true
#      tags:
#        - 'sentry'
