---
- name: Install Sentry server
  hosts: sentry
  become: true
  tasks:
    - import_tasks: tasks/install_docker.yml
      tags:
        - 'docker'

    - import_tasks: tasks/install_git.yml
      tags:
        - 'git'

    - name: Create Sentry directory
      file:
        path: /opt/sentry
        state: directory
      tags:
        - 'sentry'

    - name: Clone Sentry project
      git:
        repo: 'https://github.com/getsentry/onpremise'
        dest: /opt/sentry
      tags:
        - 'sentry'

    - name: Update Sentry configuration
      blockinfile:
        path: /opt/sentry/sentry.conf.py
        block: |
          #####################
          # GOOGLE AUTH LOGIN #
          #####################

          SENTRY_OPTIONS['auth-google.client-id'] = "{{ google_client_id }}"
          SENTRY_OPTIONS['auth-google.client-secret'] = "{{ google_client_secret }}"
      tags:
        - 'sentry'

    - name: Run Sentry install.sh
      command: ./install.sh >> installation_logs.txt
      args:
        chdir: /opt/sentry
      tags:
        - 'sentry'

    - name: Run compose to start containers
      docker_service:
        project_src: /opt/sentry
        state: present
      tags:
        - 'sentry'

#    - name: Configure administrator account
#      expect:
#        command: docker-compose run --rm web createuser
#        responses:
#          Question:
#            - sentry_admin_email
#            - sentry_admin_password
#            - sentry_admin_password
#            - 'y'
#      no_log: true
#      tags:
#        - 'sentry'
